/**
 * Set up russian capital letters no crawl
 * @param arr
 */
function init_crawl_russian_capital(arr) {
    // Russian capitals
    arr['А'] = "AΑ";
    arr['Б'] = "Б";
    arr['В'] = "BΒ";
    arr['Г'] = "Γ厂";
    arr['Д'] = "Д";
    arr['Е'] = "EΕ";
    arr['Ж'] = "Ж";
    arr['З'] = "3Յ";
    arr['И'] = "И";
    arr['К'] = "KΚ";
    arr['Л'] = "Λ人几入";
    arr['М'] = "MΜᛖ";
    arr['Н'] = "HΗዝ";
    arr['О'] = "O0ΘΟዕՕ";
    arr['П'] = "Π";
    arr['Р'] = "PΡ";
    arr['С'] = "C";
    arr['Т'] = "TΤፕ";
    arr['У'] = "YΥ";
    arr['Ф'] = "中Φቅ";
    arr['Х'] = "XΧ";
    arr['Ц'] = "Ц";
    arr['Ч'] = "Ч";
    arr['Ш'] = "山";
    arr['Щ'] = "Щ";
    arr['Ъ'] = "Ъ";
    arr['Ы'] = "Ы";
    arr['Ь'] = "b";
    arr['Э'] = "Э";
    arr['Ю'] = "Ю";
    arr['Я'] = "Я";
}

function init_crawl_russian_small(arr) {
    arr['а'] = "aα⍺";
    arr['б'] = "6ნ";
    arr['в'] = "в";
    arr['г'] = "г";
    arr['д'] = "д";
    arr['е'] = "eε";
    arr['ж'] = "ж";
    arr['з'] = "3";
    arr['и'] = "ս";
    arr['к'] = "kκ";
    arr['л'] = "λ";
    arr['м'] = "ϻ";
    arr['н'] = "н";
    arr['о'] = "σഠ";
    arr['п'] = "п";
    arr['р'] = "pρ";
    arr['с'] = "c";
    arr['т'] = "τ";
    arr['у'] = "yყ";
    arr['ф'] = "φჶ";
    arr['х'] = "xχ";
    arr['ц'] = "ц";
    arr['ч'] = "પ";
    arr['ш'] = "ա";
    arr['щ'] = "щ";
    arr['ъ'] = "ъ";
    arr['ы'] = "ы";
    arr['ь'] = "ь";
    arr['э'] = "э";
    arr['ю'] = "ю";
    arr['я'] = "я";
}